version = 0.1

[default.global.parameters]
stack_name = "kongroo-notifications"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
resolve_s3 = true
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"

[default.logs.parameters]
name = "NotificationsFunction"
