apiVersion: v1
kind: Secret
metadata:
  name: notifications-secret
  namespace: kongroo
  labels:
    app.kubernetes.io/name: notifications-api
    app.kubernetes.io/instance: notifications-api
    app.kubernetes.io/version: "0.0.3"
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: kongroo
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  RabbitMq__User: "kongroo"
  RabbitMq__Pass: "development"
