<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AWSProjectType>Lambda</AWSProjectType>
    <AssemblyName>Kongroo.Notifications</AssemblyName>
    <RootNamespace>Kongroo.Notifications</RootNamespace>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.Core" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" />
    <PackageReference Include="Amazon.Lambda.SQSEvents" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kongroo.Identity.Contracts\Kongroo.Identity.Contracts.csproj" />
    <ProjectReference Include="..\Kongroo.Payments.Contracts\Kongroo.Payments.Contracts.csproj" />
  </ItemGroup>
</Project>
